name: K8s Node Check

on:
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  check-nodes:
    # Reemplaza 'arc-runner-set' por el nombre exacto de tu Runner Scale Set
    runs-on: arc-runner-set 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Kubernetes Nodes
        run: |
          echo "Consultando los nodos del clúster..."
          kubectl get nodes -o wide
