name: Hola Mundo Pipeline

# Este pipeline se ejecuta cada vez que hay un push a cualquier rama
on:
  push:
    branches:
      - '**'

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Saludar
        run: echo "Hola Mundo"
