name: K8s Node Check

on:
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  check-nodes:
    # Reemplaza 'arc-runner-set' por el nombre exacto de tu Runner Scale Set
    runs-on: EQUIPO8 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Tools (Helm & Kubectl)
        run: |
          # Instalamos Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          
          # Instalamos Kubectl (por seguridad si el paso anterior falló)
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          # Verificar versiones
          helm version --short
          kubectl version --client
      - name: Check Kubernetes Nodes
        run: |
          echo "Consultando los nodos del clúster..."
          kubectl get nodes -o wide
      - name: Deploy Keycloak via Helm
        run: |
          # 1. Agregar el repositorio de Codecentric
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm repo update
