name: Deploy keycloak on kind 

on:
  push:
    branches:
      - main   # puedes cambiarlo por la rama que uses
#on: 
  #workflow_dispatch:

jobs:
  keycloack-setup-for-deploy:
    runs-on: arc-runner-set

    steps:
      - name: Install Kubectl
        run: |
          echo "Descargando kubectl..."
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          # Creamos una carpeta local para el binario y la añadimos al PATH
          mkdir -p $HOME/.local/bin
          mv kubectl $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 3️⃣ Instalar Helm manualmente
      - name: Install Helm
        run: |
          echo "Descargando Helm..."
          # Obtener la última versión estable
          HELM_VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases/latest | grep tag_name | cut -d '"' -f 4)
          # Descargar tar.gz de Helm para Linux amd64
          curl -Lo helm.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
            
          # Extraer el binario
          tar -zxvf helm.tar.gz
          chmod +x linux-amd64/helm

          # Mover al PATH local
          mkdir -p $HOME/.local/bin
          mv linux-amd64/helm $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH

          # Verificar instalación
          helm version
      # 4️⃣ Verificar cluster y crear namespace
      - name: Check cluster status and create namespace
        run: |
          echo "Verificando el estado del cluster..."
          kubectl cluster-info || (echo "Cluster no disponible" && exit 1)
          if ! kubectl get namespace keycloak; then
            echo "Namespace 'keycloak' no existe. Creando..."
            kubectl create namespace keycloak
          else
            echo "Namespace 'keycloak' ya existe."
          fi
      - name: Deploy Keycloak
        run: |
           set -e

           echo "Verificando namespace..."
           kubectl get namespace keycloak || kubectl create namespace keycloak

           echo "Agregando repo Helm codecentric..."
           helm repo add codecentric https://codecentric.github.io/helm-charts

           echo "Actualizando repos..."
           helm repo update

           echo "Instalando / actualizando Keycloak..."
           helm upgrade --install keycloak codecentric/keycloakx \
           --namespace keycloak \
           --values values.yaml \
           --wait \
           --timeout 5m
