name: Deploy Pod to Kind

on: 
  workflow_dispatch:

jobs:
  kind-deploy:
    runs-on: arc-runner-set

    steps:
      - name: Install Kubectl
        run: |
          echo "Descargando kubectl..."
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          # Creamos una carpeta local para el binario y la añadimos al PATH
          mkdir -p $HOME/.local/bin
          mv kubectl $HOME/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create Pod Manifest
        run: |
          cat <<EOF > pod-hola-mundo.yaml
          apiVersion: v1
          kind: Pod
          metadata:
            name: hola-mundo-kind
          spec:
            containers:
            - name: hello
              image: busybox:1.36
              command: ['sh', '-c', 'echo "¡Hola desde el clúster Kind!" && sleep 3600']
          EOF

      - name: Apply Manifest
        run: |
          # Ahora kubectl ya debería estar en el PATH
          kubectl apply -f pod-hola-mundo.yaml
          
      - name: Verify
        run: |
          kubectl get pod hola-mundo-kind
          kubectl logs hola-mundo-kind
